package com.epam.ivalua.domain;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class SupplierData {
    private String supplierName;
    private String companyName;
    private String website;
    private String comments;
    private String addressLabel;
    private String addressLine1;
    private String addressLine2;
    private String zipCode;
    private String city;
    private String country;
    private String catalogAccess;
    private String incotermPlace;
    private String bvdCode;
    private String legalForm;
    private String naiscCode;
    private String yearOfCreation;
    private String orderAddressLabel;
    private String orderAddressLine1;
    private String orderAddressLine2;
    private String orderZipCode;
    private String orderCity;
    private String orderCountry;
    private String siret;
    private String govId;
    private String taxIdNumber;
    private String duns;
    private String paymentAddressLabel;
    private String paymentAddressLine1;
    private String paymentAddressLine2;
    private String paymentZipCode;
    private String paymentCity;
    private String paymentCountry;
    private String personalTitle;
    private String identityLastName;
    private String identityFirstName;
    private String identityEmail;
    private String identityPhone;
    private String identityCellPhone;
    private String identityFax;
    private String identityPosition;
    private String approvedBy;
    private String contactAddressLabel;
    private String contactAddressLine1;
    private String contactAddressLine2;
    private String contactZipCode;
    private String contactCity;
    private String contactCountry;
    private String keywords;
    private String legalDocumentType;
    private String legalDocumentLabel;
    private String legalDocumentValidityBeginDate;
    private String legalDocumentValidityEndDate;
    private String legalDocumentComments;
    private String qualificationsCategory;
    private String qualificationsApprovedStatus;
    private String qualificationsMarkets;
    private String addALineMarket;
    private String addALineCategory;
    private String addALineNewStatusToApprove;
    private String geographicalArea;
}
